### ISSUE TITLE
Query string is incorrectly serialized for primitive parameters

### ISSUE THREAD

**Issue by raveclassic** [devexperts/swagger-codegen-ts#103]
https://github.com/devexperts/swagger-codegen-ts/blob/409e3ad8b6949324f1207301385c0b330835a4c0/src/language/typescript/3.0/serializers/operation-object.ts#L212
incorrectly serializes result of `intercalateSerializedFragmentsNEA` above because it uses unsafe `Array.prototype.join` expecting the items to be of string type but they are `Either`s.
Suggested solution: 
- use `join` from `openapi-3-utils`
- sequence list of `Either`s first

**Comment by kokovtsev** [comment]
@raveclassic can this be closed now?
