### ISSUE TITLE
Void response missing if there are response codes with non-void schema

### ISSUE THREAD

**Issue by kokovtsev** [devexperts/swagger-codegen-ts#104]
When an operation defines multiple response codes including void responses (no body), the generated code does not handle void responses.

Example:
```
responses:
  204:
    description: Successful operation
  400:
    description: Request malformed
  404:
    description: Product not found
    schema: { $ref: "#/definitions/InstrumentOperationReject" }
  422:
    description: Product deletion failed
    schema: { $ref: "#/definitions/InstrumentOperationReject" }
```

Generated code (fragment):
```
e.httpClient.chain(
	e.httpClient.request({ /* ... */ })
	pipe(
		InstrumentOperationRejectIO.decode(value),	// undefined shall not pass
		either.mapLeft(ResponseValidationError.create),
		// ...
	)
)
```

[test-api.yml.zip](https://github.com/devexperts/swagger-codegen-ts/files/4329307/test-api.yml.zip)
[test-api.zip](https://github.com/devexperts/swagger-codegen-ts/files/4329312/test-api.zip)

**Comment by raveclassic** [comment]
Thanks, @kokovtsev

**Comment by kokovtsev** [comment]
@raveclassic I guess this should have label `typescript 2.0` instead of `typescript 3.0`

Also, does 3.0 serializer treat response types differently? In 2.0, all response codes are added into the return type, but in 3.0 only `SUCCESSFUL_CODES` are considered. Is that intentional?

**Comment by kokovtsev** [comment]
@raveclassic I guess this can be closed already
