### ISSUE TITLE
Async Api parameters do not work

### ISSUE THREAD

**Issue by scink** [devexperts/swagger-codegen-ts#106]
using parameters do not generate arguments for a channel
<img width="294" alt="Screenshot 2020-03-17 at 18 59 13" src="https://user-images.githubusercontent.com/15276485/76875273-669f3080-6881-11ea-83fd-a6320c5f9536.png">
<img width="724" alt="Screenshot 2020-03-17 at 18 59 31" src="https://user-images.githubusercontent.com/15276485/76875299-7159c580-6881-11ea-8ccb-4800995b0855.png">

**Comment by scink** [comment]
any update here?

**Comment by raveclassic** [comment]
I'd gladly accept a PR for this ;)

**Comment by scink** [comment]
@raveclassic, if i could, i would open PR it long time ago

**Comment by scink** [comment]
@raveclassic could you at least add `bug` label?

**Comment by raveclassic** [comment]
Well, this is not a bug, this a just not implemented, but ok :)

**Comment by scink** [comment]
@raveclassic why not a bug? it is incorrect behaviour, isn't it?

**Comment by raveclassic** [comment]
It's `not implemented`

**Comment by scink** [comment]
fixed by 139
close it
