### ISSUE TITLE
Support passing headers to request calls

### ISSUE THREAD

**Issue by scink** [devexperts/swagger-codegen-ts#39]
it's impossible to pass headers to generated request function

**Comment by raveclassic** [comment]
Should be done with supporting header parameters in codegen: https://swagger.io/docs/specification/describing-parameters/#header-parameters and https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#headers-object

**Comment by raveclassic** [comment]
AsyncAPI already supports headers

**Comment by raveclassic** [comment]
incorporated by #57
