### ISSUE TITLE
Use swagger-parser

### ISSUE THREAD

**Issue by scink** [devexperts/swagger-codegen-ts#41]
i believe we don't have to parse and validate specs by ourself. there is a https://github.com/APIDevTools/swagger-parser that can do it better.
what do you think?
@mankdev @raveclassic @sutarmin

**Comment by raveclassic** [comment]
`swagger-parser` requires `java` - not sure we'd like to go that way

**Comment by raveclassic** [comment]
done in #3 for OpenAPI 3.0

**Comment by raveclassic** [comment]
done in #51 for Swagger 2.0

**Comment by raveclassic** [comment]
`swagger-parser` (`json-ref-schema-parser`) typings are incomplete as well as spec validation so this part remains unchanged (means stick to `io-ts`).
On the other hand `json-ref-schema-parser` offers quite handy spec resolution - so it was added
