### ISSUE TITLE
Support AsyncAPI (websockets)

### ISSUE THREAD

**Issue by raveclassic** [devexperts/swagger-codegen-ts#61]
Following https://github.com/OAI/OpenAPI-Specification/issues/523#issuecomment-356127398 there's a spec for describing schemas based on websocket communication: https://www.asyncapi.com/

We need to research possibility of adding a codec and a language for it.

**Comment by ViktoriiaLebedeva** [comment]
fdgjlkfjh;lkgfjhf

**Comment by karthickbalaji** [comment]
Would be interested to know updates here - Thanks
